import { ReactElement } from 'react'
import { GiAnimalHide, GiAnimalSkull } from 'react-icons/gi'
import { IoIosCreate } from 'react-icons/io'
import {
  IoAirplane,
  IoAmericanFootball,
  IoAnalytics,
  IoBag,
  IoBalloon,
  IoBarbell,
  IoBaseball,
  IoBasket,
  IoBasketball,
  IoBeer,
  IoBicycle,
  IoBriefcase,
  IoBulb,
  IoBus,
  IoBusiness,
  IoCar,
  IoCard,
  IoCart,
  IoCash,
  IoCloud,
  IoCloudUpload,
  IoConstruct,
  IoDesktop,
  IoDesktopOutline,
  IoFastFood,
  IoFilter,
  IoFish,
  IoFitness,
  IoFootball,
  IoGameController,
  IoGift,
  IoHeadset,
  IoHeart,
  IoHome,
  IoIceCream,
  IoLaptop,
  IoLaptopOutline,
  IoLibrary,
  IoList,
  IoMedal,
  IoPaw,
  IoPhoneLandscape,
  IoPlay,
  IoPricetag,
  IoPricetags,
  IoRestaurant,
  IoRocket,
  IoSchool,
  IoShirt,
  IoSubway,
  IoSunny,
  IoTennisball,
  IoTicket,
  IoTrailSign,
  IoTrain,
  IoTvOutline,
  IoWalk,
  IoWine,
} from 'react-icons/io5'

export const iconMap: Record<string, ReactElement> = {
  // Essencial
  food: <IoRestaurant />,
  subway: <IoSubway />,
  car: <IoCar />,
  bus: <IoBus />,
  pet: <IoPaw />,
  cart: <IoCart />,
  card: <IoCard />,
  list: <IoList />,
  clothing: <IoShirt />,
  bag: <IoBag />,
  school: <IoSchool />,

  // Lazer
  love: <IoHeart />,
  ticket: <IoTicket />,
  game: <IoGameController />,
  fastFood: <IoFastFood />,
  iceCream: <IoIceCream />,
  beer: <IoBeer />,
  trailSign: <IoTrailSign />,
  airplane: <IoAirplane />,

  // Esporte e saúde
  americanFootball: <IoAmericanFootball />,
  football: <IoFootball />,
  bicycle: <IoBicycle />,
  barbell: <IoBarbell />,
  health: <IoFitness />,

  backup: <IoCloudUpload />,
  computer: <IoDesktopOutline />,
  reapair: <IoConstruct />,
  house: <IoHome />,

  // Negócios
  rocket: <IoRocket />,
  idea: <IoBulb />,
  briefcase: <IoBriefcase />,
  business: <IoBusiness />,
  cash: <IoCash />,
  coupom: <IoPricetags />,
  gift: <IoGift />,
  graph: <IoAnalytics />,
}

export const iconsNames = Object.keys(iconMap)
