/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SignInImport } from './routes/sign-in'
import { Route as AuthGuardedImport } from './routes/_auth-guarded'
import { Route as AuthGuardedIndexImport } from './routes/_auth-guarded/index'

// Create/Update Routes

const SignInRoute = SignInImport.update({
  path: '/sign-in',
  getParentRoute: () => rootRoute,
} as any)

const AuthGuardedRoute = AuthGuardedImport.update({
  id: '/_auth-guarded',
  getParentRoute: () => rootRoute,
} as any)

const AuthGuardedIndexRoute = AuthGuardedIndexImport.update({
  path: '/',
  getParentRoute: () => AuthGuardedRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth-guarded': {
      id: '/_auth-guarded'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthGuardedImport
      parentRoute: typeof rootRoute
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInImport
      parentRoute: typeof rootRoute
    }
    '/_auth-guarded/': {
      id: '/_auth-guarded/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthGuardedIndexImport
      parentRoute: typeof AuthGuardedImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  AuthGuardedRoute: AuthGuardedRoute.addChildren({ AuthGuardedIndexRoute }),
  SignInRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_auth-guarded",
        "/sign-in"
      ]
    },
    "/_auth-guarded": {
      "filePath": "_auth-guarded.tsx",
      "children": [
        "/_auth-guarded/"
      ]
    },
    "/sign-in": {
      "filePath": "sign-in.tsx"
    },
    "/_auth-guarded/": {
      "filePath": "_auth-guarded/index.tsx",
      "parent": "/_auth-guarded"
    }
  }
}
ROUTE_MANIFEST_END */
